// Package federation provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package federation

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	ManagementKeyScopes = "ManagementKey.Scopes"
)

// DailySessionsSummary defines model for DailySessionsSummary.
type DailySessionsSummary struct {
	NextCursor      *string         `json:"next_cursor,omitempty"`
	SessionsSummary *[]DailySummary `json:"sessions_summary,omitempty"`
}

// DailySummary defines model for DailySummary.
type DailySummary struct {
	Date            *openapi_types.Date `json:"date,omitempty"`
	SessionsSummary *[]SessionsSummary  `json:"sessions_summary,omitempty"`
}

// DailyUserSession defines model for DailyUserSession.
type DailyUserSession struct {
	ConnectionTime *string             `json:"connection_time,omitempty"`
	Date           *openapi_types.Date `json:"date,omitempty"`
	EndTime        *time.Time          `json:"end_time,omitempty"`
	Location       *string             `json:"location,omitempty"`
	Received       *string             `json:"received,omitempty"`
	Sent           *string             `json:"sent,omitempty"`
	Sessions       *int                `json:"sessions,omitempty"`
	StartTime      *time.Time          `json:"start_time,omitempty"`
	User           *string             `json:"user,omitempty"`
	UserCountry    *string             `json:"user_country,omitempty"`
}

// DailyUserSessions defines model for DailyUserSessions.
type DailyUserSessions struct {
	NextCursor   *string             `json:"next_cursor,omitempty"`
	UserSessions *[]DailyUserSession `json:"user_sessions,omitempty"`
}

// SessionsSummary defines model for SessionsSummary.
type SessionsSummary struct {
	Connections *int    `json:"connections,omitempty"`
	Country     *string `json:"country,omitempty"`
	Users       *int    `json:"users,omitempty"`
}

// UserSessionsParams defines parameters for UserSessions.
type UserSessionsParams struct {
	Start   openapi_types.Date `json:"start"`
	End     openapi_types.Date `json:"end"`
	Country string             `json:"country"`
	Limit   *int               `json:"limit,omitempty"`
	Cursor  *string            `json:"cursor,omitempty"`
}

// UserSessionsParams defines parameters for UserSessions.
type UserSessionsParams struct {
	Start  openapi_types.Date `json:"start"`
	End    openapi_types.Date `json:"end"`
	Limit  *int               `json:"limit,omitempty"`
	Cursor *string            `json:"cursor,omitempty"`
}
