openapi: 3.0.3
info:
  title: common
  version: '1.0'
paths: {}
components:
  schemas:
    LabelsJson:
      description: Labels in JSON format
      type: object
      additionalProperties:
        type: string
      example: {
        "label_key_1": "label_value_1",
        "label_key_2": "label_value_2"
      }
    ConnectionIdentifiers:
      title: ConnectionIdentifiers
      type: object
      x-examples:
        example:
          value:
            user_id: Project/Authorizer/user@org
            installation_id: d1a1b2e2-d84b-4537-9a93-c4d3cd412598
            session_id: de9e0337-fb16-4669-b07d-9f261c329461
      properties:
        user_id:
          type: string
          pattern: '^([^\/]*)\/([^\/]*)\/(.*)$'
          example: Project/Authorizer/user@org
          nullable: true
        installation_id:
          format: uuid
          example: d1a1b2e2-d84b-4537-9a93-c4d3cd412598
          type: string
          nullable: true
        session_id:
          type: string
          format: uuid
          example: de9e0337-fb16-4669-b07d-9f261c329461
          nullable: true
    Error:
      title: Error
      type: object
      description: Generic error response.
      x-examples:
        example:
          value:
            result: INVALID_PEER
            error: invalid peer info
            details: invalid character '\\n' in string literal
            field: name
      properties:
        result:
          type: string
          example: INVALID_PEER
          description: Machine-readable error code.
          enum:
            - "INTERNAL_ERROR"
            - "INVALID_ARGUMENT"
            - "NOT_FOUND"
            - "ENTRY_EXISTS"
            - "STORAGE_ERROR"
            - "TUNNEL_ERROR"
            - "UNAUTHORIZED"
            - "AUTH_FAILED"
            - "INSUFFICIENT_STORAGE"
            - "SERVICE_UNAVAILABLE"
            - "CONFIGURATION_REQUIRED"
            - "FORBIDDEN"
            - "INVALID_CONFIGURATION"
            - "TOO_LONG"
            - "TOO_EARLY"
        error:
          type: string
          description: User-friendly error description.
          example: invalid peer info
        details:
          type: string
          description: 'Message, which we can put to application logs.'
          example: invalid character '\\n' in string literal
        field:
          type: string
          description: 'The name of field, caused error.'
      required:
        - result
  responses:
    OperationSuccessful:
      description: Operation successful
    ResponseError:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
