openapi: 3.0.3

info:
  title: limit-service
  version: '1.0'
  contact:
    email: support@vpnhouse.net
  description: limit-service API
paths:
  /api/limit-service/projects/limit:
    get:
      summary: List limit configs
      tags:
        - list
        - limit_config
      operationId: list-project-limit
      description: Receive full list of limit configs
      security:
        - ServiceKey: [ ]
        - ServiceName: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LimitConfig'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

    post:
      summary: Update one ore more config limits
      tags:
        - update
        - limit_config
      operationId: update-project-limit
      description: Update limit configs
      security:
        - ServiceKey: [ ]
        - ServiceName: [ ]
      responses:
        '200':
          description: OK
        '400':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/LimitConfig'

components:
  schemas:
    LimitConfig:
      title: LimitConfig
      type: object
      properties:
        project_id:
          type: string
          format: uuid
        daily_limits:
          type: array
          items:
            $ref: '#/components/schemas/DailyLimit'
      required:
          - project_id
          - daily_limits
    DailyLimit:
      title: DailyLimit
      type: object
      properties:
        auth_method:
          type: string
        limit:
          type: integer
          format: int64
          min: 0
      required:
          - auth_method
          - limit

  securitySchemes:
    ServiceKey:
      name: X-VPNHOUSE-SERVICE-KEY
      type: apiKey
      in: header
    ServiceName:
      name: X-VPNHOUSE-SERVICE
      type: apiKey
      in: header